import { Injectable } from '@angular/core';
import {Observable} from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { CommentsInterface } from '../interfaces/comments.interface';

@Injectable({
  providedIn: 'root'
})
export class CommentsService {

  constructor(
    private http : HttpClient
  ) { }

  getComments() : Observable<CommentsInterface[]> {
    return this.http.get<CommentsInterface[]>(
      'http://localhost:3000/comments'
      )
  }

  createComment(text : string, parentId : string | null) : Observable<CommentsInterface> {
    return this.http.post<CommentsInterface>('http://localhost:3000/comments', {
      body : text,
      parentId,
      //should be generated by backend
      createdAt : new Date().toISOString(),
      userId : '1',
      username : 'John'
    })
  }
}
